feat/cardAdding
Adriann77/fischkapp pull request #2
Opened 2023-12-22 21:35 UTC by Adriann77

2023-12-22 21:37 UTC, Adriann77 commented
the most difficult task so far

2024-01-02 13:54 UTC, Sumick requested changes
Overall looks really nice, we need few improvements, mostly TS related:

- [ ] Fix Prettier because its not formatting your code for sure
- [ ] Remove all `anys` and type component props properly

2024-01-02 13:54 UTC, Sumick commented on src/App.tsx
> +			setNewCard(true);
**issue:** your prettier does not work for sure. We need to fix it, because its very hard to read now

2024-01-02 13:54 UTC, Sumick commented on src/components/AppHeader.tsx
> +	createNewCard: any,
**nitpick:** We should not leave any `any`

2024-01-02 13:54 UTC, Sumick commented on src/components/AppLayout.tsx
> +export const AppLayout = (props: { children: string | number | boolean | React.ReactElement<any, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | null | un
**nitpick:** Just do `props: React.PropsWithChildren`

2024-01-02 13:54 UTC, Sumick commented on src/components/Cards.tsx
> +	answer: any;
**nitpick:** We should not leave any any

2024-01-02 13:54 UTC, Sumick commented on src/components/CardsList.tsx
> +	cards: any;
**nitpick:** `any`

2024-01-02 13:54 UTC, Sumick commented on src/components/CardsList.tsx
> +	const cardsElement = cards.map((c: { id: Key | null | undefined; heading: any; answer: any; }) => {
**nitpick:** Then you will use created type instead of this

2024-01-02 13:54 UTC, Sumick commented on src/components/NewCard.tsx
> +	const handleInputChange = (event: { target: { value: React.SetStateAction<string> } }) => {
**nitpick**: `const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>)`

2024-01-02 22:21 UTC, NerdbordMentor approved these changes
## Code Review Report

### Task Requirements Review

1. **It should show new card component when clicking on `+` button**
   - The `AppHeader` component has been modified to include a `createNewCard` function that is triggered when the `+` button is clicked.
   - The `App` component maintains the state `newCard` which is set to true when the `+` button is clicked, causing the `NewCard` component to be rendered.
   - This requirement is fulfilled.

2. **It should be possible to `Cancel` adding process**
   - The `NewCard` component includes a `Cancel` button that triggers the `resetHandler` function in the `App` component, setting the `newCard` state to false and removing the `NewCard` component from the view.
   - This requirement is fulfilled.

3. **It should be possible to proceed `Next` to the second side**
   - The `NewCard` component has a two-step process with a `Next` button that, when clicked, validates the input and moves to the second step if the input is not empty.
   - This requirement is fulfilled.

4. **It should be possible to go `Back` when being on the second side**
   - The `NewCard` component has a `Back` button that takes the user back to the first step from the second step.
   - This requirement is fulfilled.

5. **It should be possible to `Save` new card**
   - The `NewCard` component has a `Save` button that triggers the `onSaveClick` function, passing the input values for heading and answer to be saved in the state of the `App` component.
   - This requirement is fulfilled.

6. **When card is saved, it should render added card in the list**
   - The `App` component updates its `cards` state with the new card data upon saving, which is then passed down to the `CardsList` component that renders each card.
   - This requirement is fulfilled.

### Code Changes Review

- **package.json**
  - Added dependencies for form handling (`react-hook-form`) and styling (`sass`, `scss`, `style-loader`, and `css-loader`) are appropriate for the task.

- **src/App.tsx**
  - The state management for creating and saving cards is implemented correctly.
  - The use of an initial state for cards (`initialCards`) is good for testing but should eventually be replaced with a dynamic data source.
  - The function names and state variables are clear and descriptive.

- **src/components/AppHeader.tsx & src/components/AppHeader.module.css**
  - The CSS module has been replaced with an SCSS module, which is consistent with modern practices.
  - The `+` button now correctly triggers the creation of a new card.

- **src/components/AppLayout.tsx & src/components/AppLayout.module.css**
  - The CSS module has been replaced with an SCSS module, which is consistent with modern practices.

- **src/components/Cards.tsx**
  - This new component seems to be responsible for rendering individual cards, but there's no functionality for deleting cards (the Trash icon button doesn't have an onClick handler).

- **src/components/CardsList.tsx**
  - This new component correctly maps over the cards array and renders each card using the `Cards` component.

- **src/components/CssModule/\*.scss**
  - New SCSS modules have been added for styling components. They are well-structured and follow naming conventions.

- **src/components/NewCard.tsx**
  - Implements a two-step form for creating a new card with validation and error handling.
  - Uses local state to manage form steps and input values, which is appropriate.

- **src/components/icons/\*.tsx**
  - Minor changes have been made to correct attribute names (`fill-rule` to `fillRule`, etc.) in SVG elements, which is correct and necessary for JSX syntax.
  - The addition of inline styles in `plusIcon.tsx` may not be necessary if styles are managed via SCSS modules.

- **src/types/index.d.ts**
  - A TypeScript declaration file has been added for SCSS modules, which is necessary for TypeScript to understand imported SCSS module files.

### Conclusion

The code changes cover all task requirements. The implementation of adding new flashcards with validation, state management, and rendering of saved cards in a list has been achieved. There are no apparent bugs in the changed code. However, there's a missing feature for deleting cards as there's no handler attached to the Trash icon in the `Cards` component. This might be part of another task or an oversight that should be addressed in future updates.

2024-01-02 22:22 UTC, merged